## ----------------------------------------------------Section - 2-----------------------------------------------------------
###                              2) Coventional Machine Learning Model - Naive Base Classifier

#### Naive Base Classifier:
In this Project of Image classification we need to predict whether a particular celeb has a Black, Brown, Gray, Blond. the data that we have is in the range of 0 to 255 for each feature and there are 6912 features in total. so we are normalizing the data such that it now has a mean 0 and variation 1 meaning the data lies with in 0 and 1.

Naive Base classifier is of two types:
1. Gaussian Naive Base: 
Gaussian Naive base is used when we need to estimate mean and standard deviation from the features.
2. Multinomial Naive BAse: 
Multinomial Naive Base is suitable for classification with features having discrete values.

Since, the data that we are dealing in this project is Continuous data for all features we will use Gausiian Naive Base classifier for this clasification

In [1]:
import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib as mpl

from os.path import join
from tensorflow.keras import layers, models

In [2]:
# preliminary data Exploration 
hair_colours = ['black', 'blond', 'brown', 'gray']
dataset_directory = 'C:\\Users\\suhas\\Downloads\\ML Practice\\image_dataset'  ## CHANGE TO YOUR OWN DIRECTORY

images_train = np.load(join(dataset_directory, 'train_images.npy'))
labels_train = np.load(join(dataset_directory, 'train_labels.npy'))

image_size = 48
images_train_rs = images_train.reshape([-1, image_size, image_size, 3]) / 255.0
print("After reshaping image train shape is:",images_train_rs.shape)
print("After reshaping image train data is:",images_train_rs[0])

After reshaping image train shape is: (98479, 48, 48, 3)
After reshaping image train data is: [[[0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  ...
  [0.54901961 0.37254902 0.27843137]
  [0.87843137 0.79607843 0.59607843]
  [1.         0.94117647 0.89411765]]

 [[0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  ...
  [0.64705882 0.48627451 0.34901961]
  [0.93333333 0.86666667 0.7254902 ]
  [0.99607843 0.94117647 0.89019608]]

 [[0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  ...
  [0.75686275 0.61568627 0.41176471]
  [0.97647059 0.91764706 0.85098039]
  [0.98039216 0.94117647 0.8745098 ]]

 ...

 [[0.82352941 0.54117647 0.38039216]
  [0.76862745 0.50588235 0.3372549 ]
  [0.4745098  0.23921569 0.12156863]
  ...
  [0.57254902 0.37647059 0.31764706]
  [0.6        0.39607843 0.34901961]
  [0.63529412 0.427

##### Observations From preliminary data Exploration:
so we can see that images_train contains a list of size 98479 with 48 features as height for each picture, 48 features as width for each picture and a 3 channel (RGB) colour sclae for each picture (with values raning from 1 to 255). This results in 48*48*3 = 6912 features to work with.

In [3]:
Features = images_train_rs.shape[1]*images_train_rs.shape[2]*images_train_rs.shape[3]
Features   # Calculating no of featurs required per picture

6912

In [4]:
# Reshaping using Reshape()
lst1 = [None] * images_train_rs.shape[0] # creating an empty array of size 98479
for i in range(images_train_rs.shape[0]):
    lst1[i] = images_train_rs[i].reshape([-1]) # reshaping each picture to 6912 features and storing it in lst1
#print(lst)
x = np.array(lst1).reshape(images_train_rs.shape[0],Features) # converting the list to an array
print(x.shape)

(98479, 6912)


##### Train_Images data:  
we now have the trian data in the form which is accepted by all Machine learning Models (which is 98479, 6912). we can use either the x coming from reshape() for training the model. we do not need to reshape labels_train because it contains single column with 98479 values.

In [5]:
images_val = np.load(join(dataset_directory, 'val_images.npy'))
labels_val = np.load(join(dataset_directory, 'val_labels.npy'))
files_val = np.load(join(dataset_directory, 'val_files.npy'))

In [6]:
images_val_rs = images_val.reshape([-1, image_size, image_size, 3]) / 255.0

##### Observations From preliminary data Exploration:
so we can see that images_val contains a list of size 12270 with 48 features as height for each picture, 48 features as width for each picture and a 3 channel (RGB) colour sclae for each picture (with values raning from 1 to 255). This results in 48*48*3 = 6912 features to work with.

In [7]:
Features1 = images_val_rs.shape[1]*images_val_rs.shape[2]*images_val_rs.shape[3]
Features1  # calculating the no of features for each picture

6912

In [8]:
lst3 = [None] * images_val_rs.shape[0] # creating an empty array of size 12270
for i in range(images_val_rs.shape[0]):
    lst3[i] = images_val_rs[i].reshape([-1])  # reshaping each picture to 6912 features and storing it in lst3

y = np.array(lst3).reshape(images_val_rs.shape[0],Features1)  # converting the list to an array
print(y.shape)

(12270, 6912)


##### Val_Images data:  
we now have the validation data in the form which is accepted by all Machine learning Models (which is 12270, 6912). we can use y coming from reshape() for validating the model. we do not need to reshape labels_val because it contains single column with 12270 values.

### Model Fitting: 
we now have the Train_images in variable x, Val_images in y, labels_train, labels_val, so we can go further to fit the model using the training data and validate the model using the validation data. 

# Required below code in final merge file

In [9]:
# Importing and fitting Gaussian Naive Base classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model = model.fit(x, labels_train)
val_pred = model.predict(y)
print("Accuracy score for validation is:",accuracy_score(labels_val, val_pred))

Accuracy score for validation is: 0.5748981255093725


#### we can see that the Accuray score for Validation is 57.48% with Gaussian Naive base. By looking at this score we can say that the model is not performing good.

In [10]:
# reading the test data files
images_test_public = np.load(join(dataset_directory, 'test_public_images.npy'))
files_test_public = np.load(join(dataset_directory, 'test_public_files.npy'))
images_test_public_rs = images_test_public.reshape([-1, image_size, image_size, 3]) / 255.0

##### Observations From preliminary data Exploration:
so we can see that images_test contains a list of size 11921 with 48 features as height for each picture, 48 features as width for each picture and a 3 channel (RGB) colour sclae for each picture (with values raning from 1 to 255). This results in 48*48*3 = 6912 features to work with.

In [11]:
Features3 = images_test_public_rs.shape[1]*images_test_public_rs.shape[2]*images_test_public_rs.shape[3]
Features3

6912

In [12]:
lst4 = [None] * images_test_public_rs.shape[0] # creating an empty array of size 98479
for i in range(images_test_public_rs.shape[0]):
    lst4[i] = images_test_public_rs[i].reshape([-1])  # reshaping each picture to 6912 features and storing it in lst1

z = np.array(lst4).reshape(images_test_public_rs.shape[0],Features3)  # converting the list to an array
print(z.shape)

(11921, 6912)


##### Test_Images data:  
we now have the test data in the form which is accepted by all Machine learning Models (which is 11921, 6912). we can use this for predicting the model.

# Required every thing from this point in final file

In [13]:
# final model fitting and predicting
model = GaussianNB()
model = model.fit(x, labels_train)
Test_pred = model.predict(z)

In [15]:
len(Test_pred)

11921

In [17]:
import pandas as pd

In [18]:
# creating a data frame for predicted values
df1 = pd.DataFrame(Test_pred, columns=['Prediction'])
df1.tail()

Prediction
11916           1
11917           3
11918           0
11919           2
11920           1

In [19]:
# creating a data frame for files_val which contains image names
df2 = pd.DataFrame(files_test_public, columns=['ID'])
df2.tail()

ID
11916  202595.jpg
11917  202596.jpg
11918  202597.jpg
11919  202598.jpg
11920  202599.jpg

In [20]:
# Joining the two data frames through the index
GaussianNB_TestPublicData_45693242 = df2.merge(df1, left_index=True, right_index=True)
GaussianNB_TestPublicData_45693242.tail()

ID  Prediction
11916  202595.jpg           1
11917  202596.jpg           3
11918  202597.jpg           0
11919  202598.jpg           2
11920  202599.jpg           1

In [21]:
GaussianNB_TestPublicData_45693242.to_csv (r'C:\\Users\\suhas\\Downloads\\ML Practice\\GaussianNB_TestPublicData_45693242.csv', index = False, header=True)